name: garnet-analysis
channels:
  - conda-forge
  - pypi
dependencies:
  - python>=3.8
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - tqdm>=4.62.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pymatgen>=2022.0.0
  - ase>=3.22.0
  - pip
  - pip:
    - -e .